name: Metrics
on:
  # Schedule updates every monday at 1:00 UTC
  schedule: [{cron: "0 1 * * 1"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: therzka
          base: ""
          config_timezone: America/Los_Angeles
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_achievements: no
          plugin_isocalendar: yes
          extras_css: |
            h1, h2, h3 {
              color: #A654FF;
            }
            .field svg {
              color: #A654FF;
            }
            .field {
              color: #A654FF;
            }
  
