name: terminal template
on:
  workflow_dispatch: 

jobs: 
  template:
   name: create terminal
   runs-on: ubuntu-latest
   steps:
    - uses: lowlighter/metrics@latest
      with:
        template: terminal
        filename: metrics.terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata
